-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.50.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2012/8/22 19:32:17
-- Server version: 5.5.25a
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE cldn;

--
-- Definition for table area
--
DROP TABLE IF EXISTS area;
CREATE TABLE area (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT '标签名称',
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 6
AVG_ROW_LENGTH = 3276
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '板块';

--
-- Definition for table ci_sessions
--
DROP TABLE IF EXISTS ci_sessions;
CREATE TABLE ci_sessions (
  session_id VARCHAR(40) NOT NULL DEFAULT '0',
  ip_address VARCHAR(16) NOT NULL DEFAULT '0',
  user_agent VARCHAR(120) NOT NULL,
  last_activity INT(10) UNSIGNED NOT NULL DEFAULT 0,
  user_data TEXT NOT NULL,
  PRIMARY KEY (session_id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 5461
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table course
--
DROP TABLE IF EXISTS course;
CREATE TABLE course (
  id INT(11) NOT NULL AUTO_INCREMENT,
  uploader INT(11) NOT NULL COMMENT '上传者',
  name VARCHAR(255) NOT NULL COMMENT '课程名称',
  path TEXT NOT NULL COMMENT '文件路径',
  area INT(11) NOT NULL COMMENT '所属领域',
  cost INT(11) NOT NULL COMMENT '消费积分',
  list TEXT NOT NULL COMMENT '目录',
  introduction TEXT NOT NULL COMMENT '介绍',
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 10
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '课程';

--
-- Definition for table courseToMark
--
DROP TABLE IF EXISTS courseToMark;
CREATE TABLE courseToMark (
  id INT(11) NOT NULL AUTO_INCREMENT,
  course INT(11) NOT NULL COMMENT '课程',
  mark INT(11) NOT NULL COMMENT '标签',
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 55
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '课程所属标签';

--
-- Definition for table mark
--
DROP TABLE IF EXISTS mark;
CREATE TABLE mark (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT '标签名称',
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 6
AVG_ROW_LENGTH = 3276
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '标签';

--
-- Definition for table uploader
--
DROP TABLE IF EXISTS uploader;
CREATE TABLE uploader (
  id INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL COMMENT '用户名',
  `password` VARCHAR(255) NOT NULL COMMENT '密码',
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id),
  UNIQUE INDEX username (username)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '上传者';

--
-- Definition for table user
--
DROP TABLE IF EXISTS user;
CREATE TABLE user (
  id INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL COMMENT '用户名',
  `password` VARCHAR(255) NOT NULL COMMENT '密码',
  `point` INT(11) NOT NULL COMMENT '当前积分',
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id),
  UNIQUE INDEX `password` (`password`),
  UNIQUE INDEX username (username)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '读者用户';

--
-- Definition for table userBuyCourse
--
DROP TABLE IF EXISTS userBuyCourse;
CREATE TABLE userBuyCourse (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user INT(11) NOT NULL COMMENT '用户',
  course INT(11) NOT NULL COMMENT '课程',
  expiration DATE NOT NULL COMMENT '过期日期(不过期的最后一天)',
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '用户购买课程记录';

--
-- Definition for table userBuyPoint
--
DROP TABLE IF EXISTS userBuyPoint;
CREATE TABLE userBuyPoint (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user INT(11) NOT NULL COMMENT '读者用户',
  `point` INT(11) NOT NULL COMMENT '购买积分数量',
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '用户购买积分记录';

-- 
-- Dumping data for table area
--
INSERT INTO area VALUES 
  (1, '板块1', '2012-08-21 17:54:44', '0000-00-00 00:00:00'),
  (2, '板块2', '2012-08-21 17:54:49', '0000-00-00 00:00:00'),
  (3, '板块3', '2012-08-21 17:54:54', '0000-00-00 00:00:00'),
  (4, '板块4', '2012-08-21 17:54:59', '0000-00-00 00:00:00'),
  (5, '板块5', '2012-08-21 17:55:03', '0000-00-00 00:00:00');

-- 
-- Dumping data for table ci_sessions
--
INSERT INTO ci_sessions VALUES 
  ('23ca47ba7e7e9c78de0a001cb7ae9162', '127.0.0.1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8) AppleWebKit/536.25 (KHTML, like Gecko) Version/6.0 Safari/536.25', 1345627965, 'a:4:{s:9:"user_data";s:0:"";s:8:"userName";s:6:"user01";s:6:"userId";s:1:"1";s:4:"type";s:4:"user";}'),
  ('8616b39cd6bc662ed9bc8c6a4940f526', '127.0.0.1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:14.0) Gecko/20100101 Firefox/14.0.1', 1345628005, 'a:4:{s:9:"user_data";s:0:"";s:8:"userName";s:9:"uploader1";s:6:"userId";s:1:"1";s:4:"type";s:8:"uploader";}'),
  ('b865e9d0dfde3ff0f69e504d00ec61f6', '0.0.0.0', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8) AppleWebKit/536.25 (KHTML, like Gecko) Version/6.0 Safari/536.25', 1345621045, '');

-- 
-- Dumping data for table course
--
INSERT INTO course VALUES 
  (5, 1, 'PoweredByMacOSXLarge.gif', '2012_08_21_PoweredByMacOSXLarge.gif', 1, 1, '1', '1', '2012-08-22 02:52:02', '2012-08-21 22:27:49');

-- 
-- Dumping data for table courseToMark
--
INSERT INTO courseToMark VALUES 
  (53, 5, 1, '2012-08-22 17:33:56', '2012-08-22 17:33:56'),
  (54, 5, 2, '2012-08-22 17:33:56', '2012-08-22 17:33:56');

-- 
-- Dumping data for table mark
--
INSERT INTO mark VALUES 
  (1, '标签1', '2012-08-21 17:55:35', '0000-00-00 00:00:00'),
  (2, '标签2', '2012-08-21 17:55:40', '0000-00-00 00:00:00'),
  (3, '标签3', '2012-08-21 17:55:44', '0000-00-00 00:00:00'),
  (4, '标签4', '2012-08-21 17:55:47', '0000-00-00 00:00:00'),
  (5, '标签5', '2012-08-21 17:55:51', '0000-00-00 00:00:00');

-- 
-- Dumping data for table uploader
--
INSERT INTO uploader VALUES 
  (1, 'uploader1', '123456', '2012-08-21 16:42:04', '0000-00-00 00:00:00');

-- 
-- Dumping data for table user
--
INSERT INTO user VALUES 
  (1, 'user01', '123456', 1000, '2012-08-21 16:50:43', '0000-00-00 00:00:00');

-- 
-- Dumping data for table userBuyCourse
--
INSERT INTO userBuyCourse VALUES 
  (1, 1, 5, '2012-09-01', '2012-08-22 16:48:59', '0000-00-00 00:00:00');

-- 
-- Dumping data for table userBuyPoint
--
-- Table does not contain any data (it is empty)

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;